### ISSUE TITLE
Milestone 3 Feedback: Makefile

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/522-Workflows-Group-414#68]
This is what I get when I run `make all`:

```
python src/download.py --url=https://archive.ics.uci.edu/ml/machine-learning-databases/00426/Autism-Adult-Data%20Plus%20Description%20File.zip --zip_folder=data/autism_screening.zip --data_name=Autism-Adult-Data
python src/split_and_clean.py --adult_path=data/Autism-Adult-Data.csv
working
1    346
0    111
Name: A1_Score, dtype: int64

0    246
1    211
Name: A2_Score, dtype: int64

0    247
1    210
Name: A3_Score, dtype: int64

1    237
0    220
Name: A4_Score, dtype: int64

1    244
0    213
Name: A5_Score, dtype: int64

0    313
1    144
Name: A6_Score, dtype: int64

0    257
1    200
Name: A7_Score, dtype: int64

1    314
0    143
Name: A8_Score, dtype: int64

0    295
1    162
Name: A9_Score, dtype: int64

1    274
0    183
Name: A10_Score, dtype: int64

1    79
0    36
Name: A1_Score, dtype: int64

0    59
1    56
Name: A2_Score, dtype: int64

1    64
0    51
Name: A3_Score, dtype: int64

1    62
0    53
Name: A4_Score, dtype: int64

1    59
0    56
Name: A5_Score, dtype: int64

0    82
1    33
Name: A6_Score, dtype: int64

0    71
1    44
Name: A7_Score, dtype: int64

1    65
0    50
Name: A8_Score, dtype: int64

0    83
1    32
Name: A9_Score, dtype: int64

1    65
0    50
Name: A10_Score, dtype: int64

Rscript src/eda_vis.r --X_train_path=data/clean-data/Xtrain-clean-autism-screening.csv --y_train_path=data/clean-data/ytrain-clean-autism-screening.csv
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.2.0          ✔ purrr   0.3.2     
✔ tibble  2.1.3          ✔ dplyr   0.8.3.9000
✔ tidyr   1.0.0          ✔ stringr 1.4.0     
✔ readr   1.3.1          ✔ forcats 0.4.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘reshape2’

The following object is masked from ‘package:tidyr’:

    smiths

Loading required package: lattice

Attaching package: ‘caret’

The following object is masked from ‘package:purrr’:

    lift


Attaching package: ‘testthat’

The following object is masked from ‘package:dplyr’:

    matches

The following object is masked from ‘package:purrr’:

    is_null

The following object is masked from ‘package:tidyr’:

    matches

Parsed with column specification:
cols(
  .default = col_double(),
  gender = col_character(),
  ethnicity = col_character(),
  jaundice = col_character(),
  country_of_res = col_character(),
  used_app_before = col_character(),
  age_desc = col_character(),
  relation = col_character(),
  `Class/ASD` = col_character()
)
See spec(...) for full column specifications.
Parsed with column specification:
cols(
  X1 = col_double(),
  autism = col_character()
)
Warning messages:
1: Missing column names filled in: 'X1' [1] 
2: Missing column names filled in: 'X1' [1] 
python src/analysis.py --train_X=data/clean-data/Xtrain-clean-autism-screening.csv --test_X=data/clean-data/Xtest-clean-autism-screening.csv --train_y=data/clean-data/ytrain-clean-autism-screening.csv --test_y=data/clean-data/ytest-clean-autism-screening.csv --conf1=data/conf1 --conf2=data/conf2 --roc_path=img/ROC.png
Traceback (most recent call last):
  File "src/analysis.py", line 358, in <module>
    main(opt["--train_X"], opt["--test_X"],opt["--train_y"], opt["--test_y"], opt["--conf1"], opt["--conf2"], opt["--roc_path"])
  File "src/analysis.py", line 99, in main
    handle_unknown="ignore"), 
TypeError: __init__() got an unexpected keyword argument 'drop'
make: *** [img/ROC.png] Error 1
```

**Comment by Nazliozum** [comment]
Figured out it was a dependency issue on my side.
